name: Run Tests and Lint

on: [push, pull_request]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest flask openai  # Added flask and openai
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run Pylint
        run: |
          cd Tutor && pylint *.py --exit-zero
      
      - name: Run Tests
        run: |
          cd Tutor && python -m pytest tests/
